client:
  image:
    name: DEEP Client
    build: ./
    value: thedeep/deep-client
  action:
    test:
      tag: ORIGIN_BRANCH
      description: 'Running Yarn Test'
      command: bash -c 'yarn install && CI=true yarn test'
      volumes:
        - ./coverage:/code/coverage
  tags:
    ORIGIN_BRANCH:
      push: on_test
      env:
        - DOCKER_TAG_CLIENT
    LATEST:
      push: on_test
      value: latest
